/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazejercicio5;

import javax.swing.JOptionPane;

/**
 *
 * @author adalberto
 */
public class Ejercicio5 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio5
     */
    public Ejercicio5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<>();
        cmdDescuento = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtDescuento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("empresa ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 140, 40));

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Sueldo base :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoActionPerformed(evt);
            }
        });
        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, -1));

        cmbOperacion.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "El descuento por ley de politica publica", "El descuento por seguro social es: ", "El descuento por seguro forzoso es: ", "El descuento por caja de ahorro es:", "El total a pagar es: " }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        cmdDescuento.setText("Descuento");
        cmdDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(cmdDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        cmdBorrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdBorrarKeyTyped(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        txtDescuento.setEditable(false);
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 190, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void cmdDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDescuentoActionPerformed
     String re;
        double sbase,descuento1,descuento2,descuento3,descuento4,mtotal,o=0;
        int opercacion;
        
         if(txtSueldo.getText().isEmpty()){
          JOptionPane.showMessageDialog(this, "digite la cantidad de sueldo ","error",JOptionPane.ERROR_MESSAGE);
             txtSueldo.requestFocusInWindow();
             
              }
             else {
       
       
       sbase =Double.parseDouble(txtSueldo.getText());
       opercacion= cmbOperacion.getSelectedIndex();
       descuento1=(sbase*1)/100;
        descuento2=(sbase*4)/100;
        descuento3 =(sbase*0.5)/100;
        descuento4=(sbase*5)/100;
        mtotal=sbase-descuento1-descuento2-descuento3-descuento4;
        switch(opercacion){
           case 0:
                   o = descuento1;
               break;
           case 1:
                o = descuento2;
               break;
           case 2:
               o = descuento3;
               break;   
               
           case 3:
               o = descuento4;
               break;
               case 4:
               o = mtotal;
               break;
       }
                     
                     
             }
         re =String.valueOf(o);
        txtDescuento.setText(re);
    }//GEN-LAST:event_cmdDescuentoActionPerformed

    private void cmdBorrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdBorrarKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.') { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              
          }
    }//GEN-LAST:event_cmdBorrarKeyTyped

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
 char c=evt.getKeyChar(); 
             

 
 
         
 
 
          if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar()!='.') { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              
          }         
               
              
          
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       txtSueldo.setText("");
        txtDescuento.setText("");
        
        txtSueldo.requestFocusInWindow();
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSueldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdDescuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
